### ISSUE TITLE
Cannot get it working in Mx7.5.1

### ISSUE THREAD

**Issue by BlokJan** [tieniber/ActiveMenuSelector#1]
Hi,

I would like to use this widget, but it doesn't seem to work in Mx7.5.1
Does it support Mx 7 ?

Kind regards,
Jan Blok
![image](https://user-images.githubusercontent.com/30433525/42385037-fa833280-813b-11e8-821a-4fad1dcc6545.png)

**Comment by EJBroeders** [comment]
Is there an update pending? We're also hitting this issue :-(

Some more details:
* In combination with the NavigationTree widget everything crashes
* In combination with a MenuBar widget, the deselect does not work, this results in multiple activated menu items

**Comment by tieniber** [comment]
The widget was created and tested on Mendix 7.10.0 and confirmed still working on 7.16.0. 

Since it meddles with a core Mendix widget, it's very possible that it would take some tweaking to make it work in 7.5.1. I recommend you download the test project in this repository to validate your configuration. If your setup matches the working test project, then your best bet would be to upgrade your app.

I do not plan to support anything before 7.10.0 at this point, but if someone submits a pull request with a fix for earlier versions, I'd be happy to integrate it.
